@startuml creacion proyecto exitoso 
actor productoraGeneral
participant interfazWeb
participant sistemaDeValidacion
participant baseDeDatos
participant sistemaDeNotificacion

productoraGeneral -> interfazWeb: Seleccionar opcion crear proyecto
activate interfazWeb
interfazWeb -> sistemaDeValidacion: Valida datos 
activate sistemaDeValidacion
sistemaDeValidacion -> baseDeDatos: datos validados
activate baseDeDatos 
baseDeDatos -> sistemaDeNotificacion: Confirmacion creacion de proyecto
activate sistemaDeNotificacion
sistemaDeNotificacion --> baseDeDatos: envia un mensaje
deactivate sistemaDeNotificacion
baseDeDatos --> sistemaDeValidacion: confirma validacion
deactivate baseDeDatos
sistemaDeValidacion --> interfazWeb: permitir acceso
deactivate sistemaDeValidacion
interfazWeb --> productoraGeneral: muestra panel del sistema
deactivate interfazWeb

alt Creacion exitosa
    productoraGeneral --> interfazWeb: creacion exitosa
else Creacion erronea
    productoraGeneral --> interfazWeb: Creacion erronea
    end



productoraGeneral -> interfazWeb: Ingresar datos del proyecto
activate interfazWeb
interfazWeb -> sistemaDeValidacion: Verificar permisos 
activate sistemaDeValidacion
sistemaDeValidacion -> baseDeDatos: Permisos confirmados 
activate baseDeDatos
baseDeDatos -> sistemaDeNotificacion: Proyeccto guardado
activate sistemaDeNotificacion
sistemaDeNotificacion --> baseDeDatos: guardado exitoso 
deactivate sistemaDeNotificacion
baseDeDatos --> sistemaDeValidacion: permisos aprobados 
deactivate baseDeDatos
interfazWeb --> productoraGeneral: datos recibidos
deactivate interfazWeb
sistemaDeValidacion --> interfazWeb: permisos confirmados 
deactivate sistemaDeValidacion

productoraGeneral -> interfazWeb: Confirmar creacion 
activate interfazWeb
interfazWeb -> sistemaDeValidacion: solicitar guardado
activate sistemaDeValidacion
sistemaDeValidacion -> baseDeDatos: Autorizar almacenamiento 
activate baseDeDatos
baseDeDatos -> sistemaDeNotificacion: Registro completo
activate sistemaDeNotificacion
baseDeDatos -->sistemaDeValidacion: autorizacion recibida
deactivate  baseDeDatos
interfazWeb -->productoraGeneral: mostrar confirmacion exitosa
sistemaDeValidacion--> interfazWeb:notifica los reponsables asignados


@enduml





