@startuml actualizacion exitosa del estado
actor responsableDeEtapa
participant interfazDelSistema
participant Controlador
participant servicioDeEtapa
participant baseDeDatos

responsableDeEtapa -> interfazDelSistema: seleccionar proyecto y etapa
activate interfazDelSistema
interfazDelSistema -> Controlador: solicita actualizacion del sistema
activate Controlador
Controlador -> servicioDeEtapa: actualizar servicio de etapa 
activate servicioDeEtapa
servicioDeEtapa -> baseDeDatos: guardar nuevo estado 
activate baseDeDatos
baseDeDatos --> servicioDeEtapa: confirmacion guardado
servicioDeEtapa --> Controlador: estado actualizado correctamente
Controlador --> interfazDelSistema: confirmacion 
interfazDelSistema --> responsableDeEtapa: muestra mensaje de exito 
@enduml
