@startuml 01-patron-comportamiento-observer

title Patrón de Comportamiento – Observer aplicado al Sistema Productora de Videos

interface Subject {
    +agregarObserver(o : Observer)
    +quitarObserver(o : Observer)
    +notificar()
}

interface Observer {
    +actualizar(subject : Subject)
}

abstract class ElementoObservable {
    -observadores : List<Observer>
    +agregarObserver(o : Observer)
    +quitarObserver(o : Observer)
    +notificar()
}

class Proyecto
class Etapa
class Tarea

class ServicioNotificaciones {
    +actualizar(subject : Subject)
}

class ResponsableDelProyecto {
    +actualizar(subject : Subject)
}

class Coordinador {
    +actualizar(subject : Subject)
}

class DashboardAdministrador {
    +actualizar(subject : Subject)
}

ElementoObservable ..|> Subject
Proyecto ..|> ElementoObservable
Etapa ..|> ElementoObservable
Tarea ..|> ElementoObservable

ServicioNotificaciones ..|> Observer
ResponsableDelProyecto ..|> Observer
Coordinador ..|> Observer
DashboardAdministrador ..|> Observer

Subject "1" o-- "*" Observer

@enduml