@startUML Segregacion de Interfaces (ISP)


interface IUsuario {
        +autenticar(datos): string
        +validarDatos(): boolean 
        +recibirNotificacion(): String
}

interface IAdministrable{
        +gestionarProyectos(): void
        +gestionarUsuarios(): void
}

interface IComunicacion {
        +enviarMensaje():String
        +registrarFechas(): boolean
        
}

interface IArchivo {
        +subirArchivo(): void
        +permitirAcceso(): void

        }

interface IEstadistica {
        +generarReportes(): String
        +consultarEstadisticas(): void
}

Usuario ===> IUsuario 
Usuario===> IEstadistica
Sistema ===> IAdministrable
Sistema ===> IComunicacion
Sistema ===> IArchivo
Notificacion ===> IComunicacion
Adjunto ===> IArchivo
Estadistica ===> IEstadistica



@endUML