@startuml 01-solid-05-dip
title DIP — Abstracciones para clase Etapa

interface IExtractorNombre <<interface>> {
  + obtenerNombre()
}

interface IAgregarObjeto <<interface>> {
  + agregarObjeto()
}

class Etapa {
  - nombre: String
  - estado: String
  - responsableEtapa: IExtractorNombre
  - observaciones y adjuntos: List<IAgregarObjeto>
  + agregarObservacionYAdjunto()
  + actualizarResponsable()
  + actualizarEstado()
}

class Usuario  {
  - tipo: String
  - nombre: String
  - rol: String
}
class Observacion  {
  - tipo: String
  - texto: String
  - fecha: Date
  - autor: IExtractorNombre
  + agregarObservacion()
  + actualizarAutor()
}

class Adjunto  {
  - tipo: String
  - url: String
  - descripcion: String
  + agregarAdjunto()
}

class Observacion implements IAgregarObjeto {
  + agregarObjeto()
}

class Adjunto implements IAgregarObjeto {
  + agregarObjeto()
}

class Usuario implements IAgregarObjeto {
  + agregarObjeto()
}

class Usuario implements IExtractorNombre {
  + obtenerNombre()
}

Etapa --> IAgregarObjeto : observacion y adjuntos
Etapa --> IExtractorNombre : responsableEtapa
Observacion --> IExtractorNombre : autor

@enduml