@startuml diagrama

class Proyecto {
  - nombre: String
  - tipo: String
  - fechaInicio: Date
  - fechaFin: Date
  - responsableGeneral: Usuario
  - etapas: List<Etapa>
  + crearProyecto()
  + consultarProyectosActivos()
}

class Etapa {
  - nombre: String
  - estado: String
  - responsableEtapa: Usuario
  - observaciones: List<Observacion>
  + actualizarEstado()
}

class Observacion {
  - texto: String
  - fecha: Date
  + agregarObservacion()
}

class Estadistica {
  - tipo: String
  - rangoFechas: Date[]
  + consultarEstadisticas()
}

class Usuario {
  - nombre: String
  - rol: String
  + autenticar()
}

class Sistema {
  + gestionarProyectos()
  + gestionarUsuarios()
  + generarReportes()
  + notificarUsuarios()
  + accesoAutenticado()
}

Usuario --> Sistema
Usuario --> Observacion
Usuario -----> Proyecto
Usuario -----> Etapa
Proyecto -----> Etapa
Sistema -----> Estadistica
Observacion --> Etapa

@enduml