@startuml 
title agregado exitoso de observaciones 

actor usuarioAutorizado
participant "interfazSistema: conexion" as interfazSistema
participant "controlador : registrador" as controlador
participant "servicioObservacion: comentador" as servicioObservacion
participant "baseDeDatos : servidorLocal" as baseDeDatos

usuarioAutorizado -> interfazSistema: accedeAlSistema
activate interfazSistema
interfazSistema -> controlador: validaPermiso (sobreLaEtapa)
activate controlador
controlador -> servicioObservacion: verificaEtapaSeleccionada
activate servicioObservacion
servicioObservacion -> baseDeDatos: consultaDatos (deEtapa)
activate baseDeDatos
baseDeDatos --> servicioObservacion: confirmacionDeDatos
deactivate baseDeDatos
servicioObservacion --> controlador: etapaVerificada
deactivate servicioObservacion
controlador --> interfazSistema: permisosConfirmados
deactivate controlador
interfazSistema --> usuarioAutorizado: muestraPanel 
deactivate interfazSistema

usuarioAutorizado -> interfazSistema: seleccionaEtapa (delProyecto)
activate interfazSistema
interfazSistema -> controlador: presentaFormulario (web) 
activate controlador
controlador -> servicioObservacion: validaCampos (delaObservacion) 
activate servicioObservacion
servicioObservacion -> baseDeDatos: guardaObservacionYDetalles 
activate baseDeDatos
baseDeDatos --> servicioObservacion: confirmacionGuardado
deactivate baseDeDatos
servicioObservacion --> controlador: camposvalidados 
deactivate servicioObservacion
controlador --> interfazSistema: formularioPreparado
deactivate controlador
interfazSistema --> usuarioAutorizado: enviaNotificacion 
deactivate interfazSistema

usuarioAutorizado-> interfazSistema: escribeYConfirmaObservacion 
activate interfazSistema
interfazSistema -> controlador: enviaObservacionIngresado
activate controlador
controlador -> servicioObservacion: registraObservaciones (enEtapa)
activate servicioObservacion
servicioObservacion -> baseDeDatos: actualizaHistorial (deEtapas) 
activate baseDeDatos
baseDeDatos --> servicioObservacion: confirmacionHistorialActualizado
deactivate baseDeDatos 
servicioObservacion --> controlador: observacionRegistrada 
deactivate servicioObservacion
destroy servicioObservacion
controlador --> interfazSistema: operacionExitosa 
deactivate controlador
interfazSistema --> usuarioAutorizado: visualizaObservacion 
deactivate interfazSistema


@enduml